# Generated by Django 4.2.3 on 2024-11-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalMaterial',
        ),
    ]
