# Generated by Django 4.2.3 on 2024-11-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=2)),
                ('file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
