# Generated by Django 4.2.3 on 2024-11-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_educationalmaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalMaterial',
        ),
    ]
