# Generated by Django 4.2.3 on 2024-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
