# Generated by Django 4.2.3 on 2024-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_pdf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
